### ISSUE TITLE
Plans for First Release?

### ISSUE THREAD

**Issue by mstreatfield** [colour-science/colour-analysis#1]
Hi @KelSolaar,

I have built and installed colour-analysis for use where I work.

However, the way we manage external tools in our pipeline means it's easier to use packages which have a set version number/release (for us to track dependencies and updates).  Therefore, I was wondering if you had plans to cut an initial (alpha?) release of this package?

I can see that it currently requires the latest code from vispy (which isn't yet released as 0.5) based on your pull requests (vispy/vispy#901).  Presumably this meant prevent you from making an initial release?

Thanks.

**Comment by thomasmansencal** [comment]
Hey Mark,

There is currently a quite annoying issue described on https://github.com/vispy/vispy/issues/1033 that prevents me to do an initial release. I haven't checked since last time I posted on _Vispy_ side. @bollu was meant to take a look but I don't think he had time, and I also didn't had time to make a small reproducible example which means trying to pinpoint it implies grabbing the whole repo and follow my steps.

**Comment by mstreatfield** [comment]
Hi,

Thanks for the information.  

Looking again today, I also notice the current head of colour-analysis doesn't appear to be compatible with the current head of vispy (which would presumably become the 0.5 release at some point).  I get:

``` python
Traceback (most recent call last):
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/bin/colour-analysis", line 18, in <module>
    from colour_analysis.commands import main
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/lib/python2.7/site-packages/colour_analysis/__init__.py", line 45, in <module>
    from .analysis import ColourAnalysis
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/lib/python2.7/site-packages/colour_analysis/analysis.py", line 30, in <module>
    from colour_analysis.views import (
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/lib/python2.7/site-packages/colour_analysis/views/__init__.py", line 7, in <module>
    from .diagram_view import DiagramView
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/lib/python2.7/site-packages/colour_analysis/views/diagram_view.py", line 28, in <module>
    from colour_analysis.visuals import (
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/lib/python2.7/site-packages/colour_analysis/visuals/__init__.py", line 8, in <module>
    from .axis import axis_visual
  File "/home/users/markst/packages/colour_analysis/0.1.rc1/python-2.7/lib/python2.7/site-packages/colour_analysis/visuals/axis.py", line 16, in <module>
    from vispy.visuals.transforms import AffineTransform
ImportError: cannot import name AffineTransform
```

Building vispy from vispy/vispy@65b23ba3b46c549e4424522be6357b216fc85168 appears to be ok.  Looks like `AffineTransform` was merged into `MatrixTransform` in vispy/vispy@825742c76a177a1666a0d7ba1d02b3b6f37650c2 which is the following commit.  I'm afraid I'm not in a position to be able to submit a pull request to help with updating based on those changes.

Mark.

**Comment by thomasmansencal** [comment]
I'll try to get back on that soonish! I'm a bit hammered at work these days and focusing on some HDRI related side project whenever I have a bit of time but I definitely would like to have that working nicely.

**Comment by bollu** [comment]
Hey, yeah. I've been meaning to spend time to fix it, but college is hard. Seeing as it is blocking this, I'll try and get this up and running once my tests are done (Oct 29).

**Comment by mstreatfield** [comment]
Sure, no worries, thanks for the responses!

A couple of people where I work were interested in using Colour Analysis for some tasks so was just trying to get an idea of what state it's in and what I needed to build/install to get it working.

**Comment by thomasmansencal** [comment]
@bollu: No worries, better focus on your studies! :)

@mstreatfield: I'll try to get the code running ahead Vispy head this weekend.

**Comment by thomasmansencal** [comment]
The [graph_overhaul](https://github.com/colour-science/colour-analysis/tree/graph_overhaul) branch works for me with latest Vispy master.

**Comment by mstreatfield** [comment]
@KelSolaar I wanted to note that my circumstances have changed since posting this issue.  So while I'm sure a release would still be appreciated I would no longer be able to build/test it.  Sorry!  I know there were other priorities anyway, but I wanted to mention in case it did bubble up to the top at any point.
